eureka:
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-methods: [ GET,HEAD,POST,PUT,DELETE,PATCH,TRACE,CONNECT ]
      discovery:
        locator:
          enabled: true
server:
  port: 8777
  error:
    include-exception: true
    include-message: always
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn
gateway:
  admin-path: /GatewayAdmin