eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - 'http://localhost:3000'
              - 'http://localhost:4000'
      routes:
        - id: gatewayAdmin
          uri: http://127.0.0.1:${server.port}
          predicates:
            - Path=/GatewayAdmin/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Expose-Headers
logging:
  level:
    root: info
    web: debug
ez:
  auth:
    service-api-key:
      value: 98765432109876543210987654321021
  jwt:
    secret-key: 12345678901234567890123456789012
  gateway:
    rule-uri: /BASE-DATA/rules