eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: gateway
server:
  port: 8777
management:
  endpoints:
    web:
      exposure:
        include: "*"
gateway:
  cors:
    allow-credentials: true
    allowed-methods: [GET,HEAD,POST,PUT,DELETE,PATCH,TRACE,CONNECT]